{{- $fullname := include "pr-generator.fullname" . }}
{{- $ghInline := and (not .Values.secrets.github.existingSecret) (or .Values.secrets.github.privateKey .Values.secrets.github.token) }}
{{- $bbInline := and (not .Values.secrets.bitbucket.existingSecret) .Values.secrets.bitbucket.token }}
{{- if $ghInline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-github-secrets
  labels:
    {{- include "pr-generator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.github.privateKey }}
  private-key.pem: {{ .Values.secrets.github.privateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.github.token }}
  token: {{ .Values.secrets.github.token | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if $bbInline }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-bitbucket-secrets
  labels:
    {{- include "pr-generator.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.secrets.bitbucket.token | b64enc | quote }}
{{- end }}
