{{- $ghAppInline := and (eq .Values.config.providers.github.authMethod "app") .Values.secrets.github.privateKey (not .Values.secrets.github.existingSecret) -}}
{{- $ghPatInline := and (eq .Values.config.providers.github.authMethod "pat") .Values.secrets.github.token (not .Values.secrets.github.existingSecret) -}}
{{- $ghInline := or $ghAppInline $ghPatInline -}}
{{- $bbInline := and .Values.secrets.bitbucket.token (not .Values.secrets.bitbucket.existingSecret) -}}
{{- if or $ghInline $bbInline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pr-generator.fullname" . }}-secrets
  labels:
    {{- include "pr-generator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $ghAppInline }}
  {{ .Values.secrets.github.privateKeyKey }}: {{ .Values.secrets.github.privateKey | b64enc | quote }}
  {{- end }}
  {{- if $ghPatInline }}
  {{ .Values.secrets.github.tokenKey }}: {{ .Values.secrets.github.token | b64enc | quote }}
  {{- end }}
  {{- if $bbInline }}
  {{ .Values.secrets.bitbucket.tokenKey }}: {{ .Values.secrets.bitbucket.token | b64enc | quote }}
  {{- end }}
{{- end }}
