apiVersion: v2
name: pr-generator
version: 1.2.1
appVersion: "v1.2.1"
description: Helm chart for pr-generator — automated PR creation from branch patterns
type: application
home: https://github.com/devops-ia/helm-pr-generator
sources:
  - https://github.com/devops-ia/pr-generator
  - https://github.com/devops-ia/helm-pr-generator
keywords:
  - pr-generator
  - automation
  - devops
  - pull-request
maintainers:
  - email: adrianmg231189@gmail.com
    name: amartingarcia
