name: Helm Check Releases

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install updatecli
        uses: updatecli/updatecli-action@5bda7da77bf4d181bce5f807d73d832b62062acf # v3.3.0

      - name: Update dependencies
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
        run: |
          updatecli apply --config .github/updatecli/helm.yaml