name: Helm Check Releases

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install updatecli
        uses: updatecli/updatecli-action@41b9c8d707830a9daebaeaa84c1b62d60b779564 # v3.6.0

      - name: Update dependencies
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
        run: |
          updatecli apply --config .github/updatecli/helm.yaml